main = "src/worker.ts"
compatibility_date = "2024-11-11"
send_metrics = true
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1

[env.prod]
name = "price-notify-bot-prod"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[env.prod.triggers]
crons = ["*/2 1-6 * * 2-6"]

[[env.prod.kv_namespaces]]
binding = "KV"
id = "c13e6e40e1c1431fa3ea7c618ec4df38"

[env.dev]
name = "price-notify-bot-dev"

[env.dev.triggers]
crons = ["*/15 1-6 * * 2-6"]

[[env.dev.kv_namespaces]]
binding = "KV"
id = "58855527d70a4b67963948f4026a0494"
